// src/App.vue
<template>
  <v-app>
    <v-app-bar
        app
        color="blue"
        dark
    >
      <div class="d-flex align-center">
        <span class="ml-3">Calculateur cuisine</span>
      </div>
    </v-app-bar>
    <v-main>
      <calculator-view/>
    </v-main>
  </v-app>
</template>

<script lang="ts" setup>
import CalculatorView from './views/CalculatorView.vue'
</script>

// packages/cuisine-calculateur-react/src/App.tsx
import './App.css'
import { Grid, GridItem, Heading } from "@chakra-ui/react";
import { CalculatorView } from "./pages/CalculatorView.tsx";

function App() {

  return (
    <>
      <Grid>
        <GridItem bg='blue.300' p='4'>
          <Heading size='md' color='white'>Calculateur cuisine</Heading>
        </GridItem>
        <GridItem>
          <CalculatorView />
        </GridItem>
      </Grid>
    </>
  )
}

export default App
