// packages/calculateur-vue/src/CookingCalculator/CookingConfiguration.vue
<template>
  <v-row>
    <v-col>
      <v-text-field v-model.trim="cuisson.name" label="Type de cuisson"
                    variant="underlined"></v-text-field>
    </v-col>
    <v-col>
      <v-text-field v-model.number="cuisson.weight" label="Poids(en kg)"
                    variant="underlined"></v-text-field>
    </v-col>
    <v-col>
      <v-text-field v-model.number="cuisson.duration" label="Durée(en minutes)"
                    variant="underlined"></v-text-field>
    </v-col>
    <v-col>
      <v-btn @click="store.updateCooking(cuisson, props.index)">Modifier cuisson</v-btn>
    </v-col>
    <v-col>
      <v-btn @click="store.deleteCooking(props.index)">Supprimer</v-btn>
    </v-col>
  </v-row>
</template>
<script lang="ts" setup>

import {ICooking} from "@/interfaces";
import {useCookingList} from "@/store";

const store = useCookingList()
const props = defineProps<{
  index: number,
  cuisson: ICooking
}>()

const cuisson = props.cuisson
</script>

// packages/cuisine-calculateur-react/src/pages/CookingConfiguration.tsx
import { Button, HStack, Input, Text } from "@chakra-ui/react";
import { useDispatch } from "react-redux";
import { deleteCooking, updateCooking } from "../store/cookingListSlice.ts";
import { useState } from "react";
import { ICooking } from "../interfaces";


export const CookingConfiguration = (props: { cuisson: ICooking; index: number; }) => {
  const [cuisson, setCuisson] = useState(props.cuisson);
  const dispatch = useDispatch();

  const deleteCookingConfiguration = () => {
    dispatch(deleteCooking(props.index));
  };

  const updateCookingConfiguration = () => {
    dispatch(updateCooking({ cuisson, index: props.index }));
  };

  return <HStack px={"2rem"} mb={"0.5rem"}>
    <Text fontSize="sm" width={'60%'} as={"label"}>Type de cuisson: </Text>
    <Input size="sm" w="80%" placeholder="type de cuisson" value={cuisson.name} onChange={(event) => {
      const newCuisson: ICooking = {
        ...cuisson,
        name: event.target.value
      };
      setCuisson(newCuisson);
    }} />
    <Text fontSize="sm" as={"label"} width={'50%'} ml={'2rem'}>Poids (en kg): </Text>
    <Input size="sm" w="40%" placeholder="Poids (en kg)" value={cuisson.weight || ''} onChange={(event) => {
      const newCuisson: ICooking = {
        ...cuisson,
        weight: parseInt(event.target.value)
      };
      setCuisson(newCuisson);
    }} />
    <Text fontSize="sm" as={"label"} width={'50%'} ml={'2rem'}>Durée (en minutes): </Text>
    <Input size="sm" w="50%" placeholder="Durée (en minutes)" value={cuisson.duration || ''} onChange={(event) => {
      const newCuisson: ICooking = {
        ...cuisson,
        duration: parseInt(event.target.value)
      };
      setCuisson(newCuisson);
    }} />
    <Button colorScheme='green' size="sm" width={'40%'} px={'2rem'} onClick={updateCookingConfiguration}>Modifier
      cuisson</Button>
    <Button colorScheme='red' size="sm" width={'40%'} onClick={deleteCookingConfiguration}>Supprimer</Button>
  </HStack >;
}
