// src/CookingCalculator/NewCookingConfiguration.vue
<template>
  <v-row>
    <v-col>
      <v-text-field v-model="newCookingType.name" label="Nom nouveau type de cuisson"
                    variant="underlined"></v-text-field>
    </v-col>
    <v-col>
      <v-text-field v-model="newCookingType.weight" label="Poids de la nouvelle cuisson(en kg)"
                    variant="underlined"></v-text-field>
    </v-col>
    <v-col>
      <v-text-field v-model="newCookingType.duration" label="Durée nouvelle cuisson(en minutes)"
                    variant="underlined"></v-text-field>
    </v-col>
    <v-col>
      <v-btn @click="saveCooking">Enregistrer</v-btn>
    </v-col>
  </v-row>
</template>
<script lang="ts" setup>

import {ref} from "vue";
import {ICooking} from "@/interfaces";
import {useCookingList} from "@/store";

const store = useCookingList()

const newCookingType = ref<ICooking>({
  duration: 0,
  weight: 0,
  name: ''
})

const saveCooking = () => {
  store.createCookingType(newCookingType.value)
  newCookingType.value = {
    duration: 0,
    weight: 0,
    name: ''
  }
}
</script>

// packages/cuisine-calculateur-react/src/pages/NewCookingConfiguration.tsx
import { Button, HStack, Input, Text } from "@chakra-ui/react";
import { useDispatch } from "react-redux";
import { createCookingType } from "../store/cookingListSlice.ts";
import { useState } from "react";
import { ICooking } from "../interfaces";


export const NewCookingConfiguration = () => {
  const [cuisson, setCuisson] = useState<ICooking>({
    name: '', weight: 0, duration: 0
  });
  const dispatch = useDispatch();
  const createCookingConfiguration = () => {
    dispatch(createCookingType(cuisson));
  };
  return <HStack px={"2rem"} mb={"2rem"}>
    <Text as={"label"} fontSize={"sm"} width={"45%"}>Type de cuisson: </Text>
    <Input value={cuisson.name} size={"sm"} onChange={(event) => {
      setCuisson({
        ...cuisson,
        name: event.target.value
      });
    }} />
    <Text as={"label"} fontSize={"sm"} width={"50%"} ml={"2rem"}>Poids (en kg): </Text>
    <Input value={cuisson.weight} size={"sm"} onChange={(event) => {
      setCuisson({
        ...cuisson,
        weight: parseInt(event.target.value)
      });
    }} />
    <Text as={"label"} fontSize={"sm"} width={"50%"} ml={"2rem"}>Durée (en minutes): </Text>
    <Input size="sm" value={cuisson.duration} onChange={(event) => {
      setCuisson({
        ...cuisson,
        duration: parseInt(event.target.value)
      });
    }} />
    <Button colorScheme="green" size={"sm"} width={"30%"} px={"2rem"} onClick={createCookingConfiguration}>Enregistrer</Button>
  </HStack>;
}
