// src/views/CalculatorView.vue
<template>
  <v-container>
    <v-form>
      <v-row>
        <v-col>
          <h2 class="text-center">Calculateur cuisson</h2>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-btn @click="store.resetCookingList()">Remise à zero liste cuisson</v-btn>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <h4>Paramétrage type de viande</h4>
          <CookingConfiguration v-for="(cuisson, index) in cookingList" :key="index" :cuisson="cuisson" :index="index"/>
          <h4 class="mb-3 mt-3 ">Ajout nouvelle cuisson</h4>
          <NewCookingConfiguration/>
        </v-col>
      </v-row>
      <h4 class="mt-3 mb-3">Calcul de la cuisson</h4>
      <CookingCalculation :cooking-list="cookingList" :cooking-type-list="cookingTypeList"/>
    </v-form>
  </v-container>
</template>

<script lang="ts" setup>
import {computed} from 'vue'
import NewCookingConfiguration from "@/CookingCalculator/NewCookingConfiguration.vue";
import CookingCalculation from "@/CookingCalculator/CookingCalculation.vue";
import {useCookingList} from "@/store";
import CookingConfiguration from "@/CookingCalculator/CookingConfiguration.vue";

const store = useCookingList()

const cookingList = computed(() => store.cookingList)
const cookingTypeList = computed(() => store.cookingTypeList)

store.getCuissonList()

</script>

// src/pages/CalculatorView.tsx
import { Button, Heading, HStack } from "@chakra-ui/react";
import { CookingCalculation } from "./CookingCalculation.tsx";
import { NewCookingConfiguration } from "./NewCookingConfiguration.tsx";
import { CookingConfiguration } from "./CookingConfiguration.tsx";
import { useCookingList } from "@/store/useCookingList.ts";
import { useEffect } from "react";


export const CalculatorView = () => {
  const state = useCookingList();
  useEffect(() => {
    state.getCookingList()
  }, [])

  return (
    <>
      <Heading size='md' textAlign={'center'} mt={'2rem'}>Calculateur cuisson</Heading>
      <HStack px={'2rem'} mb={'3rem'}>
        <Button colorScheme={"orange"} onClick={() => state.resetCookingList()}>Remise a zero
          cuisson</Button>
      </HStack>
      <Heading size={'md'} px={'2rem'} mb={'2rem'}>Paramétrage type de viande</Heading>
      {state.cookingList.map((cuisson, index) => (
        <CookingConfiguration key={index} cuisson={cuisson} index={index} />
      ))}
      <Heading size={'md'} px={'2rem'} mb={'2rem'} mt={'2rem'}>Ajout nouvelle cuisson</Heading>
      <NewCookingConfiguration />
      <Heading size={'md'} px={'2rem'} mb={'2rem'}>Calcul de la cuisson</Heading>
      <CookingCalculation />
    </>
  )
}
