// src/CookingCalculator/CookingCalculation.vue
<template>
  <v-row>
    <v-col>
      <v-select v-model="cookingType" :items="cookingTypeList" label="Sélectionner type de viande"
                variant="underlined"></v-select>
      <v-text-field v-if="cookingType" v-model="cookingWeight" label="Poids de la viande"
                    variant="underlined"></v-text-field>
      <span v-if="cookingType && cookingWeight">{{ displayCookingDuration }}</span>
    </v-col>
  </v-row>
</template>
<script lang="ts" setup>
import {computed, ref, watch} from "vue";
import {ICooking} from "@/interfaces";
import {useCookingList} from "@/store";

const cookingType = ref('')
const cookingWeight = ref(0)
const cookingDuration = ref(0)

const store = useCookingList()

const cookingList = computed(() => store.cookingList)
const cookingTypeList = computed(() => store.cookingTypeList)

const displayCookingDuration = computed<string>(() => {
  const heure = Math.floor(cookingDuration.value / 60)
  const minutes = Math.floor(cookingDuration.value - (heure * 60))
  return `${heure} h ${minutes} (${Math.floor(cookingDuration.value)} minutes)`
})

watch(cookingWeight, () => {
  const cuisson = cookingList.value.find((cuisson: ICooking) => {
    return cuisson.name === cookingType.value
  })
  if (cuisson) {
    const poidsCuisson = parseFloat(cookingWeight.value.toString().replace(",", "."))
    cookingDuration.value = (poidsCuisson * cuisson.duration) / cuisson.weight
  }
})

watch(cookingType, () => {
  cookingWeight.value = 0
})

</script>

// src/pages/CookingCalculation.tsx
import { HStack, Input, Select, Text } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { ICooking } from "../interfaces";
import { useCookingList } from "../store/useCookingList";


export const CookingCalculation = () => {

  const { cookingList, cookingTypeList } = useCookingList();
  const [cookingType, setCookingType] = useState('');
  const [cookingWeight, setCookingWeight] = useState(0);
  const [cookingDuration, setCookingDuration] = useState(0);
  const [displayCookingDuration, setDisplayCookingDuration] = useState('');

  useEffect(() => {
    const cuisson = cookingList.find((cuisson: ICooking) => {
      return cuisson.name === cookingType;
    });
    if (cuisson) {
      const poidsCuisson = parseFloat(cookingWeight.toString().replace(",", "."));
      setCookingDuration(() => {
        return (poidsCuisson * cuisson.duration) / cuisson.weight;
      });
    }
  }, [cookingWeight, cookingList, cookingType]);
  useEffect(() => {
    const heure = Math.floor(cookingDuration / 60);
    const minutes = Math.floor(cookingDuration - (heure * 60));
    setDisplayCookingDuration(() => {
      return (isNaN(cookingDuration)) ? '' : `${heure} h ${minutes} (${Math.floor(cookingDuration)} minutes)`;
    });
  }, [cookingDuration]);

  return (
    <>
      <HStack px={"2rem"}>
        <Text fontSize={"sm"} w={"20%"} as={"label"} htmlFor="cooking-type">Type de viande:</Text>
        <Select size={"sm"} id="cooking-type" placeholder={'Sélectionner type de viande'} onChange={(event) => {
          setCookingType(event.target.value);
        }}>
          {cookingTypeList.map((cookingType, index) => (
            <option value={cookingType} key={index}>{cookingType}</option>
          ))}
        </Select>
      </HStack>
      {(cookingType != "") && (
        <HStack mt={'2rem'} mb={'2rem'} px={"2rem"}>
          <Text fontSize={"sm"} w={"20%"} as={"label"} htmlFor="weight">Poids de la cuisson:</Text>
          <Input size={"sm"} id="weight" onChange={(event) => {
            const weight = parseFloat(event.target.value.replace(",", "."))
            setCookingWeight(weight);
          }} />
        </HStack>
      )}
      {(cookingWeight > 0 && cookingDuration > 0) && (
        <Text px={"2rem"}>{displayCookingDuration}</Text>
      )}
    </>
  );
}
